server:
  port: ${PORT:9090}

spring:
  application:
    name: turf-management

  data:
    mongodb:
      uri: ${MONGODB_URI}

logging:
  level:
    root: INFO
    org.springframework.data.mongodb: DEBUG
    org.mongodb.driver: DEBUG
    org.springframework.web: DEBUG
    com.turf.turf_management: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000